---
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# IBMAIOPS INSTANCES
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


global_config:
  environment_name: ibm-aiops
  cloud_platform: existing-ocp
  # --------------------------------------------------------------------------------------------------------------------------------------
  # IBMAIOPS Pull Registires
  # --------------------------------------------------------------------------------------------------------------------------------------
  entitled_registry: cp.icr.io
  entitled_registry_user: cp
  catalog_image: icr.io/cpopen/ibm-operator-catalog:latest
  # Create Welcome Cards in IBMAIOps
  create_cards: true
  # Create App Menu Items in OCP
  create_ocp_items: true
  # Use this Password for all Instances
  global_password: P4ssw0rd!
  # Set this value to True to accept all licenses
  accept_all_licenses: False
  # Create Notifications in OCP
  create_ocp_notifications: true
  position_ocp_notifications: BannerTop
  position_final_ocp_notification: BannerTop
  # Key to decrypt Licenses
  # license_token: NONE


openshift:
- name: "mycluster"
  ocp_version: "4.12"
  cluster_name: "mycluster"
  domain_name: example.com
  openshift_storage:
  - storage_name: auto-storage
    storage_type: auto
    # Alternatively use
    #storage_name: ibm-roks-storage
    #storage_type: custom
    #ocp_storage_class_file: ibmc-file-gold-gid
    #ocp_storage_class_block: ibmc-block-gold


ibm-aiops:
- project: ibm-aiops
  instances:
  # --------------------------------------------------------------------------------------------------------------------------------------
  # INSTALL IBMAIOPS Demo Content
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: ibm-aiops-demo-content
    kind: IBMAIOpsDemoContent
    install: true


    # ---------------------------------------------------------------------
    # TRAINING
    # Train the Models based on pre-canned content

    training_create_training_temporal: true

    training_load_data_logs: true
    training_create_training_logs: true
    training_run_training_logs: true

    training_load_data_snow: true
    training_create_training_snow: true
    training_run_training_snow: true

    training_load_data_metrics: true
    training_create_training_metrics: true
    training_run_training_metrics: true

    training_data_url: https://github.com/niklaushirt/
    training_data_repo: ibm-aiops-trainingdata


    # ---------------------------------------------------------------------
    # TOPOLOGY
    # Install DemoApps Application
    install_demoapps: true
    # Install DemoApps K8s Observer
    install_demoapps_observer: true
    # Create Topology
    create_topology_templates: true
    create_topology_apps: true
    # Create Custom overlay topology
    install_custom_topology: true


    # ---------------------------------------------------------------------
    # RUNBOOKS
    # Install AWX and create Runbooks
    install_awx: true
    load_awx_playbooks: true
    integrate_awx: true
    load_runbooks: true
    create_runbook_policy: true


    # ---------------------------------------------------------------------
    # Demo UI
    install_demo_ui: true
    demoui_slack_url: https://aiopsdemohq.slack.com/sign_in_with_password
    # demoui_slack_url: https://aiops-fry2953.slack.com/x-p1624757694871-3716524482480-3705437209041/messages/C01JZLFJFMJ
    demoui_slack_user: ibm-aiopsdemo@gmail.com
    demoui_slack_pwd: P4ssw0rd!
    demoui_admin_mode: "true"
    demoui_simulation_mode: "true"

    demoui_user: demo
    # Password for the Demo UI (OVERRIDES GLOBAL PASSWORD)
    #demoui_pwd: P4ssw0rd!


    # ---------------------------------------------------------------------
    # LDAP
    install_ldap: true
    # ldap domain
    ldap_domain: ibm.com
    # ldap base
    ldap_base: dc=ibm,dc=com
    # LDAP Admin Password (OVERRIDES GLOBAL PASSWORD)
    #ldap_admin_password: P4ssw0rd!
    # LDAP Password for all Users (OVERRIDES GLOBAL PASSWORD)
    #ldap_user_password: P4ssw0rd!
    # ldap namespace
    ldap_namespace: openldap
    # ldap namespace
    ldap_register: true

    # ---------------------------------------------------------------------
    # MISC PARAMETERS (you should not modify those)
    # Create external routes (needed to create demo content)
    create_external_routes: true

    # Create a valid ingress certificate (needed for Slack integration)
    create_valid_ingress_certificate: true

    # Create Policy for Incident Creation
    create_incident_policy: true

    # Create Kafka connection for Log inception (needed to create log anomalies in the demo environment)
    create_log_connection: true

    # Create Service Account
    create_account: true


