---
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# ibm-aiops INSTANCES
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


global_config:
  # arya.png
  # bear.png
  # cersei.png
  # cersei1.png
  # daenerys.png
  # groot.png
  # hodor.png
  # hofstadter.png
  # howard.png
  # jimmy.png
  # john.png
  # king.png
  # lemmy.png
  # nightking.png
  # penny.png
  # raj.png
  # robot1.png
  # robot2.png
  # robot3.png
  # robot4.png
  # robot5.png
  # sansa.png
  # sheldon.png
  # sherlock.png
  # slash.png
  # tormund.png
  # tyrion.png
  # walker.png
  # watson.png
  environment_name: Jimmy
  cloud_platform: existing-ocp
  # --------------------------------------------------------------------------------------------------------------------------------------
  # ibm-aiops Pull Registires
  # --------------------------------------------------------------------------------------------------------------------------------------
  entitled_registry: docker-na-public.artifactory.swg-devops.com
  entitled_registry_user: nikh@ch.ibm.com
  #catalog_image: docker-na-public.artifactory.swg-devops.com/hyc-katamari-cicd-team-docker-local/katamari/relatedimages/ibm-watson-aiops-catalog:v0.1.0-20230504.1302-8a7bf836e
  #catalog_image: docker-na-public.artifactory.swg-devops.com/hyc-katamari-cicd-team-docker-local/katamari/relatedimages/ibm-watson-aiops-catalog:v0.1.0-20230505.0302-2c0f450f9
  #catalog_image: docker-na-public.artifactory.swg-devops.com/hyc-katamari-cicd-team-docker-local/katamari/relatedimages/ibm-watson-aiops-catalog:v0.1.0-20230509.0902-6eef3eab8
  #catalog_image: docker-na-public.artifactory.swg-devops.com/hyc-katamari-cicd-team-docker-local/katamari/relatedimages/ibm-watson-aiops-catalog:v0.1.0-20230511.0503-fd49d3786
  #catalog_image: docker-na-public.artifactory.swg-devops.com/hyc-katamari-cicd-team-docker-local/katamari/relatedimages/ibm-watson-aiops-catalog:v0.1.0-20230522.0502-f1d268e15
  catalog_image: docker-na-public.artifactory.swg-devops.com/hyc-katamari-cicd-team-docker-local/katamari/relatedimages/ibm-watson-aiops-catalog:v4.1.0-20230524.1401-e682bad9f
  # entitled_registry: cp.icr.io
  # entitled_registry_user: cp
  # catalog_image: icr.io/cpopen/ibm-operator-catalog:latest
  # Create Welcome Cards in ibm-aiops
  create_cards: true
  # Create App Menu Items in OCP
  create_ocp_items: true
  # Create Notifications in OCP
  create_ocp_notifications: true
  position_ocp_notifications: BannerBottom
  position_final_ocp_notification: BannerTop
  # Use this Password for all Instances
  global_password: P4ssw0rd!
  # Set this value to True to accept all licenses
  accept_all_licenses: False
  license_token: _tI3RmLx4m9EH-abvdc53DYEkbYY


openshift:
- name: "mycluster"
  ocp_version: "4.12"
  cluster_name: "mycluster"
  domain_name: example.com
  openshift_storage:
  - storage_name: auto-storage
    storage_type: auto
    # Alternatively use
    #storage_name: ibm-roks-storage
    #storage_type: custom
    #ocp_storage_class_file: ibmc-file-gold-gid
    #ocp_storage_class_block: ibmc-block-gold



ibmaiops:
- project: ibm-aiops
  instances:
  # --------------------------------------------------------------------------------------------------------------------------------------
  # ibm-aiops ibm-aiops
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: ibm-aiops
    kind: IBMAIOps
    install: false

    # current_ibmaiops_feature
    # ibm-aiops Size of the install (small: PoC/Demo, tall: Production)
    aiops_size: small
    # Custom Sizing File (aiops_size must be set to "custom")
    #custom_size_file: none
    # Name of the ibm-aiops instance
    aiops_name: ibm-cp-watson-aiops
    # Version of the catalog subscription
    subscription_channel: 4.1-dev
    # Freeze the version of the Catalog image by patching CatalogSource
    freeze_catalog: false
    # Install Feature Flags
    install_feature_flags: false

    # --------------------------------------------------------------------------------------------------------------------------------------
    # Storage Classes Override for this Instance (see comment below)
    # --------------------------------------------------------------------------------------------------------------------------------------
    #storage_class_file: automatic
    #storage_class_block: automatic

    # --------------------------------------------------------------------------------------------------------------------------------------
    # Install with CASE Files
    # --------------------------------------------------------------------------------------------------------------------------------------
    case_install: false
    case_github_url: "https://github.com/IBM/cloud-pak/raw/master/repo/case"
    case_name: ibm-cp-waiops
    case_version: 1.6.1
    case_inventory_setup: cpaiopsSetup






  # --------------------------------------------------------------------------------------------------------------------------------------
  # ibm-aiops ibm-aiops Demo Content
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: ibm-aiops-demo-content
    kind: IBMAIOpsDemoContent
    install: true


    # ---------------------------------------------------------------------
    # TRAINING
    # Train the Models based on pre-canned content

    training_create_training_temporal: false

    training_load_data_logs: false
    training_create_training_logs: false
    training_run_training_logs: false

    training_load_data_snow: false
    training_create_training_snow: false
    training_run_training_snow: false

    training_load_data_metrics: false
    training_create_training_metrics: false
    training_run_training_metrics: false

    # Create feature flag Training (Seasonality and XinY)
    training_create_training_experimental: false

    training_data_url: https://github.com/niklaushirt/
    training_data_repo: ibm-aiops-trainingdata


    # ---------------------------------------------------------------------
    # TOPOLOGY
    # Install DemoApps Application
    install_demoapps: false
    # RobotShop interface color (classic/white)
    robotshop_color: white
    # Install DemoApps K8s Observer
    install_demoapps_observer: false
    # Create Topology
    create_topology_templates: true
    create_topology_apps: true
    # Create Custom overlay topology
    install_custom_topology: false


    # ---------------------------------------------------------------------
    # RUNBOOKS
    # Install AWX and create Runbooks
    install_awx: false
    load_awx_playbooks: false
    integrate_awx: false
    load_runbooks: false
    create_runbook_policy: false


    # ---------------------------------------------------------------------
    # Demo UI
    install_demo_ui: false
    demoui_slack_url: https://aiopsdemohq.slack.com/sign_in_with_password
    # demoui_slack_url: https://aiops-fry2953.slack.com/x-p1624757694871-3716524482480-3705437209041/messages/C01JZLFJFMJ
    demoui_slack_user: ibm-aiopsdemo@gmail.com
    demoui_slack_pwd: P4ssw0rd!
    demoui_admin_mode: "true"
    demoui_simulation_mode: "true"

    demoui_user: demo
    # Password for the Demo UI (OVERRIDES GLOBAL PASSWORD)
    #demoui_pwd: P4ssw0rd!


    # ---------------------------------------------------------------------
    # LDAP
    install_ldap: false
    # ldap domain
    ldap_domain: ibm.com
    # ldap base
    ldap_base: dc=ibm,dc=com
    # LDAP Admin Password (OVERRIDES GLOBAL PASSWORD)
    #ldap_admin_password: P4ssw0rd!
    # LDAP Password for all Users (OVERRIDES GLOBAL PASSWORD)
    #ldap_user_password: P4ssw0rd!
    # ldap namespace
    ldap_namespace: openldap
    # ldap namespace
    ldap_register: false

    # ---------------------------------------------------------------------
    # MISC PARAMETERS (you should not modify those)
    # Create external routes (needed to create demo content)
    create_external_routes: false

    # Create a valid ingress certificate (needed for Slack integration)
    create_valid_ingress_certificate: false

    # Create Policy for Story Creation
    create_incident_policy: false

    # Create Kafka connection for Log inception (needed to create log anomalies in the demo environment)
    create_log_connection: false

    # Create Service Account
    create_account: false

    # Install Webhook Probe
    install_webhook_probe: false
    subscription_channel: v3.7


    # ---------------------------------------------------------------------
    # OUTPUT
    # Print all logins
    print_logins: false
    # Open the relevant Web UIs
    open_web_ui: false



