#*************************************************************************************************************************************************
#--------------------------------------------------------------------------------------------------------------------------------------
# IBMAIOPS INSTANCE WITHOUT DEMO CONTENT
#--------------------------------------------------------------------------------------------------------------------------------------
#*************************************************************************************************************************************************

global_config:
  # --------------------------------------------------------------------------------------------------------------------------------------
  # Passwords and Licenses
  # --------------------------------------------------------------------------------------------------------------------------------------
  # Use this Password for all Instances
  global_password: CHANGEME


  # Available Names: Aajla, AIOPS, Amy, Anakin, Arya, Austin, Bart, Batman, Bear, Bob, Cara, Cassian, Cersei, Cersei1, Chewbacca, CP4AIOPS, Daenerys, Daffy, Darth, Demo, Dexter, Dilbert, Finn, Freddie, Grogu, Groot, Han, Harley, Hodor, Hofstadter, Howard, Hulk, James, Jimmy, John, Joker, Jyn, King, Kirk, Kurt, Lando, Leia, Lemmy, Luke, Nightking, Obiwan, Padme, Penny, Picard, Prince, Raj, Rey, Robin, Robot1, Robot2, Robot3, Robot4, Robot5, Sabine, Sansa, Sheldon, Sherlock, Slash, Spiderman, Spock, Strange, Superman, Tormund, Tyrion, Walker, Watson, Wedge,,,
  environment_name: Bear
  cloud_platform: existing-ocp
  # Set this value to True to accept all licenses
  accept_all_licenses: False
  # Key to decrypt Licenses
  #license_token: NONE


  # --------------------------------------------------------------------------------------------------------------------------------------
  # Pull Registires
  # --------------------------------------------------------------------------------------------------------------------------------------
  entitled_registry: cp.icr.io
  entitled_registry_user: cp
  catalog_image: icr.io/cpopen/ibm-aiops-catalog:latest
  current_supported_aiops_version: v4.8

  # --------------------------------------------------------------------------------------------------------------------------------------
  # Notifications and Cards
  # --------------------------------------------------------------------------------------------------------------------------------------
  # Create Welcome Cards in ibm-aiops
  create_cards: true
  # Create App Menu Items in OCP
  create_ocp_items: true
  # Create Notifications in OCP
  create_ocp_notifications: true
  position_ocp_notifications: BannerBottom
  position_final_ocp_notification: BannerTop





# *************************************************************************************************************************************************
# -------------------------------------------------------------------------------------------------------------------------------------
# OpenShift Configuration
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

openshift:

- name: "mycluster"
  ocp_version: "4.15"
  cluster_name: "mycluster"
  domain_name: example.com
  openshift_storage:
  - storage_name: auto-storage
    storage_type: auto
    # Alternatively use
    #storage_name: ibm-roks-storage
    #storage_type: custom
    #ocp_storage_class_file: ibmc-file-gold-gid
    #ocp_storage_class_block: ibmc-block-gold




#*************************************************************************************************************************************************
#--------------------------------------------------------------------------------------------------------------------------------------
# IBM AIOPS Configuration
#--------------------------------------------------------------------------------------------------------------------------------------
#*************************************************************************************************************************************************

ibmaiops:


#--------------------------------------------------------------------------------------------------------------------------------------

# CloudPak for AIOps Base Install

#--------------------------------------------------------------------------------------------------------------------------------------
# Changing the project name / namespace is at your own risk. some things might break, I do not test this!

- project: ibm-aiops
  instances:
  - name: ibm-aiops
    kind: IBMAIOps
    install: true

    # --------------------------------------------------------------------------------------------------------------------------------------
    # Install Sizing
    # current_ibm-aiops_feature
    # ibm-aiops Size of the install (small: PoC/Demo, large: Production)
    aiops_size: small
    # Custom Sizing File (aiops_size must be set to "custom")
    #custom_size_file: none

    # --------------------------------------------------------------------------------------------------------------------------------------
    # Install Details
    # Name of the ibm-aiops instance
    aiops_name: ibm-aiops
    # Version of the catalog subscription
    subscription_channel: v4.6
    # Freeze the version of the Catalog image by patching CatalogSource
    freeze_catalog: true

    # Enable Log Anomaly and Similar Tickets
    logAnomalyDetection: true
    # Topology Model (application/service)
    topologyModel: application


    
    
    # Install Feature Flags
    install_feature_flags: true


    # --------------------------------------------------------------------------------------------------------------------------------------
    # Storage Classes Override for this Instance
    #storage_class_file: automatic
    #storage_class_block: automatic

    # --------------------------------------------------------------------------------------------------------------------------------------
    # Install with CASE Files
    # --------------------------------------------------------------------------------------------------------------------------------------
    case_install: false
    case_github_url: "https://github.com/IBM/cloud-pak/raw/master/repo/case"
    case_name: ibm-cp-waiops
    case_version: 1.13.1
    case_inventory_setup: cpaiopsSetup


