---
# tasks file for aiops
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#     ________  __  ___   __________    ___         __                        __  _
#    /  _/ __ )/  |/  /  /  _/_  __/   /   | __  __/ /_____  ____ ___  ____ _/ /_(_)___  ____
#    / // __  / /|_/ /   / /  / /     / /| |/ / / / __/ __ \/ __ `__ \/ __ `/ __/ / __ \/ __ \
#  _/ // /_/ / /  / /  _/ /  / /     / ___ / /_/ / /_/ /_/ / / / / / / /_/ / /_/ / /_/ / / / /
# /___/_____/_/  /_/  /___/ /_/     /_/  |_\__,_/\__/\____/_/ /_/ /_/\__,_/\__/_/\____/_/ /_/
#
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Ansible Install Playbook V0.1
#
#  IBM AIOps
#
#  ©2025 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"


# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# TEST SOME STUFF
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

- name: 🛰️  START - INIT CHECKS
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"






# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Checks
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

- name:   🔐 INIT CHECKS - Check Entitlement provided
  fail: msg="Please provide IBM Entitlement Pull Secret Key/Token (Get it from here https://myibm.ibm.com/products-services/containerlibrary)"
  when: "cp_entitlement_key is not defined"

- name:   🔐 INIT CHECKS - Check Entitlement provided
  fail: msg="Please provide IBM Entitlement Pull Secret Key/Token (Get it from here https://myibm.ibm.com/products-services/containerlibrary)"
  when: '"<REGISTRY_TOKEN>" in cp_entitlement_key'

- name:   ✅ INIT CHECKS - Check ENTITLED REGISTRY
  fail: msg="! ENTITLED REGISTRY NOT DEFINED"
  when: global_config.entitled_registry is not defined

- name:   ✅ INIT CHECKS - Check ENTITLED REGISTRY USER
  fail: msg="! ENTITLED REGISTRY USER NOT DEFINED"
  when: global_config.entitled_registry_user is not defined

- name:   ✅ INIT CHECKS - Check CATALOG IMAGE
  fail: msg="! CATALOG IMAGE NOT DEFINED"
  when: global_config.catalog_image is not defined

- name:   ✅ INIT CHECKS - Check VERSION
  shell: |
    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: ibm-aiops-notification-version-missmatch
    spec:
      backgroundColor: '#ff7777'
      color: '#000'
      location: "BannerTop"
      text: '⚠️ This automation has been tested with CP4AIOPS {{global_config.current_supported_aiops_version}} - You are trying to install {{current_feature.subscription_channel}} - Proceed at your own risk!'    
    EOF
  ignore_errors: true
  args:
    executable: /bin/bash
  when: global_config.current_supported_aiops_version | default("v4.6") !=  current_feature.subscription_channel 
