
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Install AWX (open source Ansible Tower)
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


# --------------------------------------------------------------------------------------------------------------------------------------
# Install AWX
# --------------------------------------------------------------------------------------------------------------------------------------
# Create AWX

- name: 🛰️  START - INSTALL AWX
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"


- name: Log
  shell: |
    export MESSAGE="Installing AWX"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_ibmaiops_feature.kind}}.log
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_ibmaiops_feature.kind}}.log
  ignore_errors: true

- name: 📣 OCP CONSOLE - Create Openshift NOTIFICATION
  shell: |
    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: ibm-aiops-notification
    spec:
      backgroundColor: '#ffd500'
      color: '#000'
      location: {{global_config.position_ocp_notifications | default("BannerTop")}}
      text: 'Installing {{current_ibmaiops_feature.kind}} - AWX'    
    EOF
  ignore_errors: true
  args:
    executable: /bin/bash
  when: global_config.create_ocp_notifications | default(true) == true  


# --------------------------------------------------------------------------------------------------------------------------------------
# AWX Operator REMOVED BY REDHAT
# --------------------------------------------------------------------------------------------------------------------------------------

# - name: 🚀 AWX - Create AWX Operator
#   kubernetes.core.k8s:
#     state: present
#     namespace: awx
#     src: ./templates/awx/operator-install.yaml
#   ignore_errors: true

# --------------------------------------------------------------------------------------------------------------------------------------
# AWX Operator Install official https://github.com/ansible/awx-operator
# --------------------------------------------------------------------------------------------------------------------------------------
- name: 🚀 AWX - Create AWX Operator
  shell: |
    mkdir awx
    cd awx
    git clone https://github.com/ansible/awx-operator.git
    cd awx-operator

    git checkout tags/2.19.1

    cat <<EOF >>kustomization.yaml
    apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization
    resources:
      # Find the latest tag here: https://github.com/ansible/awx-operator/releases
      - github.com/ansible/awx-operator/config/default?ref=2.19.1

    # Set the image tags to match the git version from above
    images:
      - name: quay.io/ansible/awx-operator
        newTag: 2.19.1

    # Specify a custom namespace in which to install AWX
    namespace: awx
    EOF

    kubectl apply -k .
  ignore_errors: true
  args:
    executable: /bin/bash



# --------------------------------------------------------------------------------------------------------------------------------------
# Wait for Operator ready
# --------------------------------------------------------------------------------------------------------------------------------------
- name: 🕦 CHECK -  Wait AWX Operator
  shell: |
    NUM_PODS=$(oc get po -n awx | grep operator| grep 2/2| wc -l)
    echo $NUM_PODS
  register: kubectl_num_pods
  until: kubectl_num_pods.stdout|int >= 1
  retries: 100
  delay: 15


# Create aiops-topology-service-account
- name:   🚀 AWX - Patch default storage class if non defined
  shell: |
    export default=$(oc get storageclass -oyaml|grep "is-default-class"|wc -l|tr -d " ")
    echo $default
    if [ $default -lt 1 ]; then
        echo "Patching"
        kubectl patch storageclass {{ AIOPS_STORAGE_CLASS_FILE }} -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
      else
        echo "Patching not needed"
      fi
  ignore_errors: true



- name:  🌏 AWX  - Getting AWX UID
  shell: |
    export uidrange=$(oc get project awx -o jsonpath="{.metadata.annotations.openshift\.io/sa\.scc\.uid-range}"|cut -d "/" -f 1)
    echo $uidrange
  ignore_errors: true
  register: output   
- name: 🚀 AWX  - Set AWX UID
  set_fact: AWX_UIDRANGE={{ output.stdout_lines[0] | default(1000810000)}} 
- name: 🟣  OUTPUT
  debug:
    var: AWX_UIDRANGE
    verbosity: 1
        



- name: 🚀 AWX - Create AWX Instance (while waiting for IBM AIOPS Installation to progress)
  kubernetes.core.k8s:
    state: present
    namespace: awx
    template: ./templates/awx/awx-deploy-cr.j2
  ignore_errors: true

