
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Install IBM AIOPS
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

- name: 🛰️  START - IBM AIOPS INSTALLATION
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"


- name: Log
  shell: |
    export MESSAGE="Installing IBM AIOps Instance"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_ ibm-aiops_feature.kind}}.log
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_ ibm-aiops_feature.kind}}.log
  ignore_errors: true

- name: 📣 OCP CONSOLE - Create Openshift NOTIFICATION
  shell: |
    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: ibm-aiops-notification
    spec:
      backgroundColor: '#ffd500'
      color: '#000'
      location: {{global_config.position_ocp_notifications | default("BannerTop")}}
      text: 'Installing {{current_ ibm-aiops_feature.kind}} - Creating IBM AIOps Instance'    
    EOF
  ignore_errors: true
  when: global_config.create_ocp_notifications | default(true) == true  



- name:  🚀 IBM AIOPS INSTALL - Create Custom Profile ConfigMap
  shell: |
    oc apply -n {{ current_ibm-aiops_cluster.project }} -f {{current_ ibm-aiops_feature.custom_size_file | default('none')}}
  register: kubectl_get_pods
  when: current_ ibm-aiops_feature.aiops_size | default('none') == "custom"



- name:  🚀 IBM AIOPS INSTALL - Install Custom Resource with Custom Profile - INSTALL IBM AIOPS
  kubernetes.core.k8s:
    state: present
    template: './templates/aiops/4_aiops-install-template-custom.j2'
  when: current_ ibm-aiops_feature.aiops_size == "custom"





- name:  🚀 IBM AIOPS INSTALL - Install Custom Resource - INSTALL IBM AIOPS
  kubernetes.core.k8s:
    state: present
    template: './templates/aiops/4_aiops-install-template.j2'
  when: current_ ibm-aiops_feature.aiops_size != "custom"

    