     
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ibm-aiops-inject-lags-anomaly
  namespace: ibm-aiops-demo-ui
spec:
  template:
    spec:
      serviceAccountName: ibm-aiops-demo-ui-admin
      serviceAccount: ibm-aiops-demo-ui-admin 


      containers:
        - name: install
          image: quay.io/niklaushirt/ibm-aiops-tools:2.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "2024Mi"
              cpu: "1200m"
          command:
            - /bin/sh
            - -c
            - |
              #!/bin/bash
              #set -x

              export INSTALL_REPO="https://github.com/niklaushirt/ibm-aiops-deployer.git -b dev_latest"
              export ITERATIONS=10



              echo "***************************************************************************************************************************************************"
              echo "***************************************************************************************************************************************************"
              echo "                                                                                                                                                   "
              echo " 🚀 Inject LAGS Anomaly                                                                                                                                                  "
              echo "                                                                                                                                                   "
              echo "***************************************************************************************************************************************************"
              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo " 🚀 Getting Installation source from GitHub"
              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo "   📥 Clone Repo $INSTALL_REPO"
              git clone $INSTALL_REPO
              cd ibm-aiops-deployer


              echo "   ------------------------------------------------------------------------------------------------------------------------------"
              echo "    🚀 Starting Data Load"
              echo "   ------------------------------------------------------------------------------------------------------------------------------"
              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo "This Repo includes those latestet Commits"
              echo "------------------------------------------------------------------------------------------------------------------------------"
              git log|head -n 17
              echo ""
              echo ""

              echo "ITERATIONS: $ITERATIONS"
              for i in `seq 1 $ITERATIONS`;
              do
                echo "   ------------------------------------------------------------------------------------------------------------------------------"
                echo "    📶 Injecting Data $i/$ITERATIONS"
                echo "   ------------------------------------------------------------------------------------------------------------------------------"
                ./tools/01_demo/inject-gs-anomaly-kafka.sh
                echo "   ------------------------------------------------------------------------------------------------------------------------------"
                echo "    ⏳ Wait 30 seconds"
                echo "   ------------------------------------------------------------------------------------------------------------------------------"
                sleep 30
              done

              echo "*****************************************************************************************************************************"
              echo " ✅ DONE"
              echo "*****************************************************************************************************************************"
            
              sleep 15
              oc delete job  -n ibm-aiops-demo-ui ibm-aiops-inject-lags-anomly 


      restartPolicy: Never
  backoffLimit: 500


