

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Open Doc
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


- name: Log
  shell: |
    export MESSAGE=" 🌏 Update IBMAIOps Cards"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_ibmaiops_feature.kind}}.log
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_ibmaiops_feature.kind}}.log
  ignore_errors: true

- name: 📣 OCP CONSOLE - Create Openshift NOTIFICATION
  shell: |
    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: ibm-aiops-notification
    spec:
      backgroundColor: '#ffd500'
      color: '#000'
      location: {{global_config.position_ocp_notifications | default("BannerTop")}}
      text: 'Installing {{current_ibmaiops_feature.kind}} - Update IBMAIOps Cards'    
    EOF
  ignore_errors: true
  args:
    executable: /bin/bash
  when: global_config.create_ocp_notifications | default(true) == true  





  - name:  🌏 ZEN CARDS - TEST
    shell: |
      echo "User: admin@instana.local - Password: {{current_ibmaiops_feature.instana_admin_pass  | default( global_config.global_password )}} "
      echo "User: administrator - Password: {{current_ibmaiops_feature.turbo_admin_password  | default( {{global_config.global_password}} )}} "
      echo "User: administrator - Password: {{current_ibmaiops_feature.turbo_admin_password  | default( '{{global_config.global_password}}' )}} "
    ignore_errors: true
    register: output
    args:
      executable: /bin/bash
  - name: 🟣  OUTPUT
    debug:
      var: output.stdout_lines


