#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#         ________  __  ___     ___    ________       
#        /  _/ __ )/  |/  /    /   |  /  _/ __ \____  _____
#        / // __  / /|_/ /    / /| |  / // / / / __ \/ ___/
#      _/ // /_/ / /  / /    / ___ |_/ // /_/ / /_/ (__  ) 
#     /___/_____/_/  /_/    /_/  |_/___/\____/ .___/____/  
#                                           /_/
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing ibm-aiops
#
#  CloudPak for Watson AIOps
#
#  ©2023 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Get a Cluster from TechZone: https://techzone.ibm.com/collection/custom-roks-vmware-requests
#   Geograpy: prefer Dallas or London (others might be slower)
#   Worker node count: 5
#   Flavour: b3c.32x128 ❗ 
#   OpenShift Version: 4.12
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
#  - IBM Operator
#  - ibm-aiops
#  - ibm-aiops Demo Content
#     - OpenLDAP & Register with ibm-aiops
#     - RobotShop Demo App
#     - Demo Service Account 
#     - AWX (Open Source Ansible Tower) with preloaded Playbooks
#     - Train Models
#       - Create Training Definitions (TG, LAD, CR, SI, MET. Turn off RSA) 
#       - Create Training Data (LAD, SNOW, MET) 
#       - Train Models (TG, LAD, CR, SI, MET) 
#     - Topology
#       - Create K8s Observer
#       - Create ASM merge rules
#       - Load ASM merge Topology
#       - Create ibm-aiops Application
#     - Creates valid certificate for Ingress (Slack) 
#     - External Routes (Flink, Topology, ...)
#     - Disables ASM Service match rule 
#     - Create Policy Creation for Stories and Runbooks 
#  - ELK
#  - Turbonomic
#  - Instana
    # uiServer:
    #   container:
    #     resources:
    #       limits:
    #         cpu: 1000m
    #         ephemeral-storage: 5Gi
    #         memory: 1Gi
    #       requests:
    #         cpu: 1000m
    #         ephemeral-storage: 1Gi
    #         memory: 1Gi
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
---
apiVersion: v1                     
kind: Namespace
metadata:
  name: ibm-aiops-installer
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-aiops-installer-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ibm-aiops-installer

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nfs-client-provisioner
subjects:
  - kind: ServiceAccount
    name: nfs-client-provisioner
    namespace: nfs-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: nfs-client-provisioner
  namespace: nfs-provisioner

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ibm-aiops-install-configuration-instana
  namespace: ibm-aiops-installer
immutable: false
data:
  # Get your key from here https://myibm.ibm.com/products-services/containerlibrary
  ENTITLED_REGISTRY_KEY: >-
    eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJJQk0gTWaaaaaaaaaaaaa0NzQzMjgsImp0aSI6IjRjYTM3ODkwMzExNjQxZDdiMDJhMjRmMGMxMWMwYmZhIn0.Z-rqfSLJA-R-ow__tI3RmLx4m9EH-abvdc53DYEkbYY
  INSTALLATION_CONFIG.yaml: >+
    #*************************************************************************************************************************************************
    #--------------------------------------------------------------------------------------------------------------------------------------
    # Global Configuration
    #--------------------------------------------------------------------------------------------------------------------------------------
    #*************************************************************************************************************************************************

    global_config:
      # Available Names: Arya,Bear,Cersei,Cersei1,Daenerys,Groot,Hodor,Hofstadter,Howard,Jimmy,John,King,Lemmy,Nightking,Penny,Raj,Robot1,Robot2,Robot3,Robot4,Robot5,Sansa,Sheldon,Sherlock,Slash,Tormund,Tyrion,Walker,Watson
      environment_name: Arya
      cloud_platform: existing-ocp

      # --------------------------------------------------------------------------------------------------------------------------------------
      # Pull Registires
      # --------------------------------------------------------------------------------------------------------------------------------------
      entitled_registry: cp.icr.io
      entitled_registry_user: cp
      catalog_image: icr.io/cpopen/ibm-operator-catalog:latest

      # --------------------------------------------------------------------------------------------------------------------------------------
      # Notifications and Cards
      # --------------------------------------------------------------------------------------------------------------------------------------
      # Create Welcome Cards in ibm-aiops
      create_cards: true
      # Create App Menu Items in OCP
      create_ocp_items: true
      # Create Notifications in OCP
      create_ocp_notifications: true
      position_ocp_notifications: BannerBottom
      position_final_ocp_notification: BannerTop


      # --------------------------------------------------------------------------------------------------------------------------------------
      # Passwords and Licenses
      # --------------------------------------------------------------------------------------------------------------------------------------
      # Use this Password for all Instances
      global_password: CHANGEME
      # Set this value to True to accept all licenses
      accept_all_licenses: False
      license_token: _tI3RmLx4m9EH-abvdc53DYEkbYY


    # *************************************************************************************************************************************************
    # -------------------------------------------------------------------------------------------------------------------------------------
    # OpenShift Configuration
    # --------------------------------------------------------------------------------------------------------------------------------------
    # *************************************************************************************************************************************************

    openshift:

    - name: "mycluster"
      ocp_version: "4.15"
      cluster_name: "mycluster"
      domain_name: example.com
      openshift_storage:
      - storage_name: auto-storage
        storage_type: auto
        # Alternatively use
        #storage_name: ibm-roks-storage
        #storage_type: custom
        #ocp_storage_class_file: ibmc-file-gold-gid
        #ocp_storage_class_block: ibmc-block-gold




    #*************************************************************************************************************************************************
    #--------------------------------------------------------------------------------------------------------------------------------------
    # IBM AIOPS Configuration
    #--------------------------------------------------------------------------------------------------------------------------------------
    #*************************************************************************************************************************************************

    ibmaiops:


    - project: ibm-aiops-addons
      instances:
      # --------------------------------------------------------------------------------------------------------------------------------------
      # IBM AIOPS INSTANA
      # --------------------------------------------------------------------------------------------------------------------------------------

      - name: ibm-aiops-instana
        kind: Instana
        install: true
        # Check Version here https://artifact-public.instana.io/artifactory/rel-generic-instana-virtual/infrastructure/kubectl/
        instana_version: 269-0
        # Can be large, medium (default), small 
        instana_size: medium

        # ---------------------------------------------------------------------
        # INSTANA LICENSE
        sales_key: 'NONE'
        agent_key: 'NONE'

        # ---------------------------------------------------------------------
        # INSTANA DATASTORE
        instana_beeinstana_mirrors: 2  # Set to 1 for single node installations

        # ---------------------------------------------------------------------
        # INSTANA ADMIN LOGIN
        # Admin User Name
        instana_admin_user: "admin@instana.local"
        #instana_admin_user: "demo"
        # Admin User Password (OVERRIDES GLOBAL PASSWORD)
        #instana_admin_pass: 'CHANGEME'
        
        # ---------------------------------------------------------------------
        # INSTALL INSTANA AGENT
        install_agent: true

        # --------------------------------------------------------------------------------------------------------------------------------------
        # INTEGRATIONS
        integrate_ibmaiops: true
        #integrate_turbonomic: true
        
        # --------------------------------------------------------------------------------------------------------------------------------------
        # Storage Classes Override for this Instance (see comment below)
        # --------------------------------------------------------------------------------------------------------------------------------------
        #storage_class_file: automatic
        #storage_class_block: automatic

  INSTALL_REPO: 'https://github.com/niklaushirt/ibm-aiops-deployer.git -b dev_latest'
















# ------------------------------------------------------------------------------------------------------------------------------------------------------------------
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------
# DO NOT MODIFY BELOW
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------
---
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ibm-aiops-instana-install
  namespace: ibm-aiops-installer
spec:
  serviceAccountname: ibm-aiops-installer-admin
  template:
    metadata:
      labels:
        app: ibm-aiops-installer
    spec:
      containers:
        - name: install
          image: quay.io/niklaushirt/ibm-aiops-tools:2.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "2024Mi"
              cpu: "1200m"
          command:
            - /bin/sh
            - -c
            - |
              #!/bin/bash
              #set -x
              echo "***************************************************************************************************************************************************"
              echo "***************************************************************************************************************************************************"
              echo "                                                                                                                                                   "
              echo " 🚀 Install IBM AIOps                                                                                                                                                  "
              echo "                                                                                                                                                   "
              echo "***************************************************************************************************************************************************"
              echo "***************************************************************************************************************************************************"
              echo "  "
              echo "  "
              echo "  ⏳ INSTALLATION START TIMESTAMP: $(date)"
              echo ""
              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo " 📥 Housekeeping"
              oc delete ConsoleNotification --all>/dev/null 2>/dev/null 
              oc delete job  -n ibm-aiops-installer --ignore-not-found $(oc get job -n ibm-aiops-installer|grep load-|awk '{print$1}'):-notfound  --ignore-not-found>/dev/null 2>/dev/null 
              oc delete pod  -n ibm-aiops-installer $(oc get po -n ibm-aiops-installer|grep load-|awk '{print$1}'):-notfound  --ignore-not-found>/dev/null 2>/dev/null 
              echo ""
              echo ""

              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo " 🚀 Getting Installation source from GitHub"
              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo "   📥 Clone Repo $INSTALL_REPO"
              git clone $INSTALL_REPO
              cd ibm-aiops-deployer

              echo ""
              echo ""
              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo "   🔎 This Repo includes those latestet Commits"
              git log|head -n 17
              echo ""
              echo ""

              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo " 📝 Config File"         
              cat /tmp/config-file/INSTALLATION_CONFIG.yaml


              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo " 🚀 Starting Installation"
              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo ""

              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo " 🚀 Prepare Ansible"
              pip -q install openshift pyyaml kubernetes
              echo ""
              echo ""

              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo " 🚀 Launching Ansible Playbook"
              export ANSIBLE_LOG_PATH=/tmp/ansible.log
              ansible-playbook ./ansible/00_ibm-aiops-install.yaml -e "config_file_path=/tmp/config-file/INSTALLATION_CONFIG.yaml" -e cp_entitlement_key=$ENTITLED_REGISTRY_KEY
              echo ""
              echo ""

              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo "  ⏳ INSTALLATION END TIMESTAMP: $(date)"
              echo ""


              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo " 🚀 Finalize Installation"
              ./tools/90_finalizeInstallation.sh
              echo ""

              while true
              do
                sleep 1000
              done

          env:
          - name: INSTALL_REPO
            valueFrom:
              configMapKeyRef:
                name: ibm-aiops-install-configuration-instana
                key: INSTALL_REPO
          - name: TURBO_LICENSE
            valueFrom:
              configMapKeyRef:
                name: ibm-aiops-install-configuration-instana
                key: TURBO_LICENSE
                optional: true
          - name: INSTANA_SALES_KEY
            valueFrom:
              configMapKeyRef:
                name: ibm-aiops-install-configuration-instana
                key: INSTANA_SALES_KEY
                optional: true
          - name: INSTANA_AGENT_KEY
            valueFrom:
              configMapKeyRef:
                name: ibm-aiops-install-configuration-instana
                key: INSTANA_AGENT_KEY
                optional: true
          - name: ENTITLED_REGISTRY_KEY
            valueFrom:
              configMapKeyRef:
                name: ibm-aiops-install-configuration-instana
                key: ENTITLED_REGISTRY_KEY
                optional: true
          volumeMounts:
            - name: config-file
              mountPath: /tmp/config-file
      volumes:
        - name: config-file
          configMap:
            name: ibm-aiops-install-configuration-instana
            items:
            - key: INSTALLATION_CONFIG.yaml
              path: INSTALLATION_CONFIG.yaml
      restartPolicy: Never
  backoffLimit: 400


