apiVersion: apps/v1
kind: Deployment
metadata:
  name: eum-sim
  labels:
    app: eum-sim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eum-sim
  template:
    metadata:
      labels:
        app: eum-sim
    spec:
      containers:
      - name: eum-sim
        image: docker.io/niklaushirt/eum-sim:1.0
        env:
          - name: API_URL
            value: https://eum.apps.661ce247548608001edc5f96.cloud.techzone.ibm.com
          - name: API_KEY
            value: f2iA_Z5VRCeWTqVE2s4WSw
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: CONFIG
            value: config-shop
            # Change this per environment
          - name: BACKENDS
            value: demoeu
          - name: PORT
            value: '8000'
          - name: TZ
            value: Europe/London
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 100Mi
        imagePullPolicy: Always
