apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-simulator
  labels:
    app: mobile-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobile-simulator
  template:
    metadata:
      labels:
        app: mobile-simulator
    spec:
      containers:
      - name: mobile-simulator
        image: quay.io/niklaushirt/eum-sim-mobile:1.0
        env:
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: REPORT_ENV
            value: eu
        resources:
          limits:
            cpu: 200m
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 100Mi
