apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: datalayer-api
spec:
  #host: datalayer-api.${CLUSTER_APPS_HOST}
  port:
    targetPort: secure-port
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: aiops-ir-core-ncodl-api
    weight: 100
  wildcardPolicy: None