

#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#     ________  __  ___   __________    ___         __                        __  _
#    /  _/ __ )/  |/  /  /  _/_  __/   /   | __  __/ /_____  ____ ___  ____ _/ /_(_)___  ____
#    / // __  / /|_/ /   / /  / /     / /| |/ / / / __/ __ \/ __ `__ \/ __ `/ __/ / __ \/ __ \
#  _/ // /_/ / /  / /  _/ /  / /     / ___ / /_/ / /_/ /_/ / / / / / / /_/ / /_/ / /_/ / / / /
# /___/_____/_/  /_/  /___/ /_/     /_/  |_\__,_/\__/\____/_/ /_/ /_/\__,_/\__/_/\____/_/ /_/
#
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing IBM Instana
#
#  IBM Instana
#
#  ©2025 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
#  - IBM Instana Demo Content
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
 
 
 
- name: 🟣🟣🟣🟣🟣🟣  INSTALLATION MODULE START - {{current_feature.kind}}
  debug: 
    msg: 
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "      🟡🟡🟡🟡🟡  🚀 IBM IT Automation - INSTALLING {{current_feature.kind}} 🟡🟡🟡🟡🟡                                                        "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Check Login
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************



- name: 📣 OCP CONSOLE - Create Openshift NOTIFICATION
  shell: |
    export AIOPS_NAMESPACE=$(oc get po -A|grep aiops-orchestrator-controller |awk '{print$1}')
    appURL=$(oc get routes -n $AIOPS_NAMESPACE-demo-ui ibm-aiops-demo-ui  -o jsonpath="{['spec']['host']}")|| true
    OPENSHIFT_ROUTE=$(oc get route -n openshift-console console -o jsonpath={.spec.host})    
    INSTALL_POD=$(oc get po -n ibm-installer -l app=ibm-installer --no-headers|grep "Running"|grep "1/1"|grep 'install-instana'|awk '{print$1}')

    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: ibm-aiops-notification-main
    spec:
      backgroundColor: '#141a6b'
      color: '#fff'
      location: {{global_config.position_final_ocp_notification | default("BannerBottom")}}
      text: 'Installing  {{current_feature.kind}} - '    
      link:
          href: "https://$OPENSHIFT_ROUTE/k8s/ns/ibm-installer/pods/$INSTALL_POD/logs"
          text: Open Logs  
    EOF
  ignore_errors: true
  args:
    executable: /bin/bash



- name:   🚀 INITIALIZATION - Get Cluster FQDN
  shell: |
    CLUSTER_ROUTE=$(oc get routes console -n openshift-console | tail -n 1 2>&1 ) 
    CLUSTER_FQDN=$( echo $CLUSTER_ROUTE | awk '{print $2}')
    echo ${CLUSTER_FQDN##*console.}
  register: CLUSTER_NAME


- name:   🚀 INITIALIZATION - Check Cluster Connectivity
  fail: msg="You must be logged in to the server!"
  when: CLUSTER_NAME.stdout==""



- name: 🟣 Installing {{current_feature.kind}} with the following configuration
  debug:
    var: current_feature


- name:  🟣 Storage Class Parameters - SPECIFIC INSTANCE"
  debug:
    msg:
    - "** Installation Options for SPECIFIC INSTANCE ***********************************************************************"
    - " Storage Class File Override:      {{ current_feature.storage_class_file}}"
    - " Storage Class Block Override:     {{ current_feature.storage_class_block}}"
    - ""
  when: current_feature.storage_class_file is defined


- name:  🟣 Storage Class Parameters - GLOBAL"
  debug:
    msg:
    - "** Installation Options from GLOBAL ***********************************************************************"
    - " Storage Class File Override:      {{ ocp_storage_class_file }}"
    - " Storage Class Block Override:     {{ ocp_storage_class_block }}"
    - ""
  when: current_feature.storage_class_file is not defined and ocp_storage_class_file is defined





# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INITIALIZATION
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Placeholder for customization
- name: 🟡🟡🟡 Initialize Custom Hook
  include_tasks: 00_init-custom-hook.yaml

# Initialize Logging
- name: 🟡🟡🟡 Initialize Logging
  include_tasks: "{{role_path}}/../ibm-install-global/tasks/01_init-logging.yaml"

- name: 🟡🟡🟡 Get Storage Class
  include_tasks: "{{role_path}}/../ibm-install-global/tasks/05_init-get-storage-class.yaml"

  
# Start block
- name: 🟡🟡🟡 Start Logging
  include_tasks: "{{role_path}}/../ibm-install-global/tasks/90-log-start.yaml"




# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INSTALL DEMO APPS
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Create Demo Apps
- name: (001/002) - 🟡🟡🟡🟡🟡🟡🟡🟡🟡  Create the Demo Apps 
  include_tasks: 23_addons-demoapps.yaml
  when: current_feature.install_demoapps | default(false) == true


- name: (002/002) - 🟡🟡🟡🟡🟡🟡🟡🟡🟡  Create Home UI
  include_tasks: 27_ibm-home-ui.yaml
  when: current_feature.create_home_ui | default(false) == true


- name: 🟡🟡🟡 Install OCP Menu Item
  include_tasks: 91_addons-create-ocp-tools-menu.yaml
  when: global_config.create_ocp_items | default(true) == true  


- name: 🟡🟡🟡 End Logging
  include_tasks: "{{role_path}}/../ibm-install-global/tasks/91-log-end.yaml"


- name: 📣 OCP CONSOLE - Create Openshift NOTIFICATION
  shell: |
    oc delete ConsoleNotification --all>/dev/null 2>/dev/null
    export appURL=$(oc get routes -n instana-core dev-aiops -o jsonpath="{['spec']['host']}")|| true
    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
        name: ibm-aiops-notification-main
    spec:
        backgroundColor: '#009a00'
        color: '#fff'
        link:
            href: "https://$appURL"
            text: Instana
        location: BannerTop
        text: "✅ IBM Instana is installed in this cluster. 🚀 Access it here:"
    EOF

  ignore_errors: true
  args:
    executable: /bin/bash




- name: 🟣🟣🟣🟣🟣🟣  ✅ INSTALLATION MODULE DONE - {{current_feature.kind}}
  debug: 
    msg:  

    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "       ✅ IBM IT Automation - DONE INSTALLING {{current_feature.kind}}                                                                                 "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
