#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#     ________  __  ___   __________    ___         __                        __  _
#    /  _/ __ )/  |/  /  /  _/_  __/   /   | __  __/ /_____  ____ ___  ____ _/ /_(_)___  ____
#    / // __  / /|_/ /   / /  / /     / /| |/ / / / __/ __ \/ __ `__ \/ __ `/ __/ / __ \/ __ \
#  _/ // /_/ / /  / /  _/ /  / /     / ___ / /_/ / /_/ /_/ / / / / / / /_/ / /_/ / /_/ / / / /
# /___/_____/_/  /_/  /___/ /_/     /_/  |_\__,_/\__/\____/_/ /_/ /_/\__,_/\__/_/\____/_/ /_/
#
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing IBM AIOps
#
#  IBM AIOps
#
#  ©2025 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
 

- hosts: localhost
  #become: true
  #vars_files: {{ config_file }}
  #vars_files: ./configs/ibm-aiops-roks-all.yaml

  tasks:
  - name: 🚀 MAIN INSTALLATION LOOP - Install Module
    debug: 
      msg: 
      - "***************************************************************************************************************************************************"
      - "***************************************************************************************************************************************************"
      - "***************************************************************************************************************************************************"
      - "***************************************************************************************************************************************************"
      - "                                                                                                                                                   "
      - "       🟣🟣🟣🟣🟣🟣🟣🟢🟢🟢 IBM IT Automation - INSTALLATION                                                                      "
      - "                                                                                                                                                   "
      - "***************************************************************************************************************************************************"
      - "***************************************************************************************************************************************************"
      - "***************************************************************************************************************************************************"
      verbosity: 2


  - name: 🛠️  Config File Path
    debug:
      var: config_file_path
      verbosity: 2

  - name: 🛠️  Ansible check config file exists
    stat:
      path: "{{config_file_path}}"
    register: p

  - name: 🛠️  Ansible check config file exists
    debug:
      msg: "  ✅ Config File exists..."
      verbosity: 2
    when: p.stat.exists

  - name: 🛠️  Fail if not exists
    fail: msg="The specified config file {{config_file_path}} does not exist"
    when: p.stat.exists == False
      
  - name: 🛠️  Import Config File
    include_vars:
      file: "{{config_file_path}}"
      name: all_config


  # Loop over all Clusters
  - name: ♻️  Deploy IBM IT Automation Assets - Loop over Clusters
    include_role:
      name: tools-install-main-loop
    loop: "{{ all_config.ibmitautomation | default([]) }}"
    loop_control:
      loop_var: current_ibm_feature

