#*************************************************************************************************************************************************
#--------------------------------------------------------------------------------------------------------------------------------------
# Global Configuration
#--------------------------------------------------------------------------------------------------------------------------------------
#*************************************************************************************************************************************************

global_config:
  # Available Names: Aajla, AIOPS, Amy, Anakin, Arya, Austin, Bart, Batman, Bear, Bob, Cara, Cassian, Cersei, Cersei1, Chewbacca, CP4AIOPS, Daenerys, Daffy, Darth, Demo, Dexter, Dilbert, Finn, Freddie, Grogu, Groot, Han, Harley, Hodor, Hofstadter, Howard, Hulk, James, Jimmy, John, Joker, Jyn, King, Kirk, Kurt, Lando, Leia, Lemmy, Luke, Nightking, Obiwan, Padme, Penny, Picard, Prince, Raj, Rey, Robin, Robot1, Robot2, Robot3, Robot4, Robot5, Sabine, Sansa, Sheldon, Sherlock, Slash, Spiderman, Spock, Strange, Superman, Tormund, Tyrion, Walker, Watson, Wedge,,,
  environment_name: Bear
  cloud_platform: existing-ocp

  # --------------------------------------------------------------------------------------------------------------------------------------
  # Pull Registires
  # --------------------------------------------------------------------------------------------------------------------------------------
  entitled_registry: cp.icr.io
  entitled_registry_user: cp
  catalog_image: icr.io/cpopen/ibm-aiops-catalog:latest
  current_supported_aiops_version: v4.6

  # --------------------------------------------------------------------------------------------------------------------------------------
  # Notifications and Cards
  # --------------------------------------------------------------------------------------------------------------------------------------
  # Create Welcome Cards in ibm-aiops
  create_cards: true
  # Create App Menu Items in OCP
  create_ocp_items: true
  # Create Notifications in OCP
  create_ocp_notifications: true
  position_ocp_notifications: BannerBottom
  position_final_ocp_notification: BannerTop


  # --------------------------------------------------------------------------------------------------------------------------------------
  # Passwords and Licenses
  # --------------------------------------------------------------------------------------------------------------------------------------
  # Use this Password for all Instances
  global_password: P4ssw0rd!
  # Set this value to True to accept all licenses
  accept_all_licenses: False
  # Key to decrypt Licenses
  license_token: _tI3RmLx4m9EH-abvdc53DYEkbYY


# *************************************************************************************************************************************************
# -------------------------------------------------------------------------------------------------------------------------------------
# OpenShift Configuration
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

openshift:

- name: "mycluster"
  ocp_version: "4.15"
  cluster_name: "mycluster"
  domain_name: example.com
  openshift_storage:
  - storage_name: auto-storage
    storage_type: auto
    # Alternatively use
    #storage_name: ibm-roks-storage
    #storage_type: custom
    #ocp_storage_class_file: ibmc-file-gold-gid
    #ocp_storage_class_block: ibmc-block-gold




#*************************************************************************************************************************************************
#--------------------------------------------------------------------------------------------------------------------------------------
# IBM AIOPS Configuration
#--------------------------------------------------------------------------------------------------------------------------------------
#*************************************************************************************************************************************************

ibmitautomation:


# --------------------------------------------------------------------------------------------------------------------------------------
# IBM CONCERT
# --------------------------------------------------------------------------------------------------------------------------------------
- project: ibm-concert
  instances:
  - name: ibm-concert
    kind: IBMConcert
    install: false
    
    # ---------------------------------------------------------------------
    # CONCERT REGISTRY
    prod_registry: cp.icr.io
    private_registry_location: cp.icr.io
    prod_user: cp

    # ---------------------------------------------------------------------
    # PROJECT SETTINGS
    project_operator: ibm-concert-operators 
    project_instance: ibm-concert 

    # ---------------------------------------------------------------------
    # CONTAINER RUNTIME
    docker_exe: podman 

    # --------------------------------------------------------------------------------------------------------------------------------------
    # Storage Classes Override for this Instance (see comment below)
    # --------------------------------------------------------------------------------------------------------------------------------------
    #storage_class_file: automatic
    #storage_class_block: automatic


  - name: ibm-concert-demo-content
    kind: IBMConcertDemoContent
    install: true

    # ---------------------------------------------------------------------
    # DEMO CONTENT
    install_demo_content: true


    # ---------------------------------------------------------------------
    # LDAP
    install_ldap: true
    # ldap domain
    ldap_domain: ibm.com
    # ldap base
    ldap_base: dc=ibm,dc=com
    # LDAP Admin Password (OVERRIDES GLOBAL PASSWORD)
    #ldap_admin_password: CHANGEME
    # LDAP Password for all Users (OVERRIDES GLOBAL PASSWORD)
    #ldap_user_password: CHANGEME
    # ldap namespace
    ldap_namespace: openldap
    # Integrate AIOps Login with OpenLDAP 
    ldap_register: true
    # Integrate OpenShift Login with OpenLDAP
    integrate_ocp_openldap: true





# --------------------------------------------------------------------------------------------------------------------------------------
# IBM TURBONOMIC
# --------------------------------------------------------------------------------------------------------------------------------------
- project: ibm-turbonomic
  instances:

  - name: ibm-turbonomic
    kind: IBMTurbonomic
    install: false
    turbo_version: 8.13.3

    # --------------------------------------------------------------------------------------------------------------------------------------
    # Storage Classes Override for this Instance (see comment below)
    # --------------------------------------------------------------------------------------------------------------------------------------
    #storage_class_file: automatic
    #storage_class_block: automatic


  - name: ibm-turbonomic-demo-content
    kind: IBMTurbonomicDemoContent
    install: false
    # Admin User Password (OVERRIDES GLOBAL PASSWORD)
    #turbo_admin_password: CHANGEME
    # ---------------------------------------------------------------------
    # Create Demo User
    create_user: true
    # Demo User Name
    demo_user: demo
    # Demo User Password (OVERRIDES GLOBAL PASSWORD)
    #turbo_demo_password: CHANGEME
    # ---------------------------------------------------------------------
    # Create Groups
    group_vcenter_vms: true
    group_robotshop: true
    group_licensing: true

    # ---------------------------------------------------------------------
    # Create Targets
    target_instana: true
    # ---------------------------------------------------------------------
    # Create Memory and CPU hogs
    resource_hogs: false
    # ---------------------------------------------------------------------
    # Create Metrics server, DIF integration and RobotShop BuisnessApp
    metrics_dif: true
    # ---------------------------------------------------------------------
    # Turbo License (optional)
    turbo_license: NONE
    # ---------------------------------------------------------------------
    # Create a valid ingress certificate when on ITZ
    create_valid_ingress_itz: false






# --------------------------------------------------------------------------------------------------------------------------------------
# IBM INSTANA
# --------------------------------------------------------------------------------------------------------------------------------------
- project: ibm-instana
  instances:

  - name: ibm-instana
    kind: IBMInstana
    install: false

    # ---------------------------------------------------------------------
    # INSTANA LICENSE
    sales_key: 'NONE'
    agent_key: 'NONE'

    # ---------------------------------------------------------------------
    # INSTANA ADMIN LOGIN
    # Admin User Name
    instana_admin_user: "admin@instana.local"
    #instana_admin_user: "demo"
    # Admin User Password (OVERRIDES GLOBAL PASSWORD)
    #instana_admin_pass: 'CHANGEME'
    
    # ---------------------------------------------------------------------
    # INSTALL INSTANA AGENT
    install_agent: true

    # --------------------------------------------------------------------------------------------------------------------------------------
    # INTEGRATIONS
    integrate_ibmaiops: true
    #integrate_turbonomic: true
    
    # --------------------------------------------------------------------------------------------------------------------------------------
    # Storage Classes Override for this Instance (see comment below)
    # --------------------------------------------------------------------------------------------------------------------------------------
    #storage_class_file: automatic
    #storage_class_block: automatic

    # ---------------------------------------------------------------------
    # INSTANA PARAMETERS
    # Check Version here https://artifact-public.instana.io/artifactory/rel-generic-instana-virtual/infrastructure/kubectl/
    instana_version: 277-2
    # Can be large, medium (default), small 
    instana_size: medium
    # Can be 1 or 3 (default is 3) 
    instana_backend_scale: 3 
    instana_beeinstana_mirrors: 2  # Set to 1 for single node installations



  - name: ibm-instana-demo-content
    kind: IBMInstanaDemoContent
    install: false

